package edu.cnu.mdi.view.demo.geoslice;

import java.awt.geom.Point2D;

import edu.cnu.mdi.geometry.Line;
import edu.cnu.mdi.geometry.Plane;

/**
 * Synthetic three-dimensional shell surrounding one detector-like region.
 *
 * <p>
 * A {@code Shell3D} is a simple sector-like envelope around one group of
 * synthetic wires. It is not a general solid modeling class. Its purpose is to
 * provide a shared model object for two demos:
 * </p>
 *
 * <ul>
 * <li>the 2D MDI slice view, where the shell produces a 2D polygon by
 * intersecting a constant-phi plane, and</li>
 * <li>the companion MDI-3D view, where the shell is drawn directly as a
 * wireframe so readers can see the object that the 2D slice cuts through.</li>
 * </ul>
 */
public final class Shell3D {

    /** Minimum azimuthal extent of the shell, in degrees. */
    private static final double PHI_MIN_DEG = -30.0;

    /** Maximum azimuthal extent of the shell, in degrees. */
    private static final double PHI_MAX_DEG = 30.0;

    /** Longitudinal span of the synthetic chamber, in world units. */
    private static final double Z_SPAN = 260.0;

    /** Slope of the radial envelope as a function of z. */
    private static final double R_SLOPE = 0.30;

    /** Approximate spacing between synthetic layers, in world units. */
    private static final double LAYER_SPACING = 7.0;

    /** Extra longitudinal margin around the wire envelope. */
    private static final double Z_MARGIN = 14.0;

    /** Extra radial margin around the wire envelope. */
    private static final double R_MARGIN = 5.0;

    /**
     * Extra z shift applied to the shell-corner lines.
     *
     * <p>
     * This roughly matches the stereo-like z shift used by the synthetic wires,
     * but is slightly larger so the shell still encloses the wire endpoints.
     * </p>
     */
    private static final double SHELL_Z_SHIFT = 11.0;

    /** Zero-based region index. */
    private final int regionIndex;

    /** Base radial coordinate for this region. */
    private final double chamberR0;

    /** Base z coordinate for this region. */
    private final double chamberZ0;

    /** Minimum z coordinate of the shell envelope. */
    private final double zMin;

    /** Maximum z coordinate of the shell envelope. */
    private final double zMax;

    /**
     * Create a shell around one chamber-like region.
     *
     * @param regionIndex zero-based region index
     * @param chamberR0 base radial coordinate
     * @param chamberZ0 base z coordinate
     */
    private Shell3D(int regionIndex, double chamberR0, double chamberZ0) {
        this.regionIndex = regionIndex;
        this.chamberR0 = chamberR0;
        this.chamberZ0 = chamberZ0;
        this.zMin = chamberZ0 - Z_MARGIN;
        this.zMax = chamberZ0 + Z_SPAN + Z_MARGIN;
    }

    /**
     * Create a shell for the given chamber-like region.
     *
     * @param chamber zero-based chamber index
     * @param chamberR0 base radial coordinate
     * @param chamberZ0 base z coordinate
     * @return shell for the given chamber
     */
    public static Shell3D forChamber(int chamber, double chamberR0, double chamberZ0) {
        return new Shell3D(chamber, chamberR0, chamberZ0);
    }

    /**
     * Return the minimum shell azimuth.
     *
     * @return minimum shell phi in degrees
     */
    public static double getPhiMinDeg() {
        return PHI_MIN_DEG;
    }

    /**
     * Return the maximum shell azimuth.
     *
     * @return maximum shell phi in degrees
     */
    public static double getPhiMaxDeg() {
        return PHI_MAX_DEG;
    }

    /**
     * Return the zero-based region index.
     *
     * @return zero-based region index
     */
    public int getRegionIndex() {
        return regionIndex;
    }

    /**
     * Return the minimum z coordinate of the shell envelope.
     *
     * @return minimum shell z
     */
    public double getZMin() {
        return zMin;
    }

    /**
     * Return the maximum z coordinate of the shell envelope.
     *
     * @return maximum shell z
     */
    public double getZMax() {
        return zMax;
    }

    /**
     * Return the human-readable shell label.
     *
     * @return label such as {@code "region 2"}
     */
    public String label() {
        return "region " + (regionIndex + 1);
    }

    /**
     * Create the shell intersection polygon for a constant-phi slice.
     *
     * <p>
     * This method creates four 3D shell-corner lines spanning the sector in
     * azimuth and intersects those lines with the current constant-phi plane.
     * Thus the shell moves with the slider by the same mechanism as the wires:
     * both are generated by real intersections with the current slice plane.
     * </p>
     *
     * @param phiDeg current slice azimuth, in degrees
     * @return four slice-coordinate points, or {@code null} if out of range
     */
    public Point2D.Double[] slicePolygon(double phiDeg) {
        if (phiDeg < PHI_MIN_DEG || phiDeg > PHI_MAX_DEG) {
            return null;
        }

        Plane plane = Plane.constantPhiPlane(phiDeg);

        edu.cnu.mdi.geometry.Point p00 =
                intersectCornerLine(plane, rMin(zMin), zMin);

        edu.cnu.mdi.geometry.Point p10 =
                intersectCornerLine(plane, rMin(zMax), zMax);

        edu.cnu.mdi.geometry.Point p11 =
                intersectCornerLine(plane, rMax(zMax), zMax);

        edu.cnu.mdi.geometry.Point p01 =
                intersectCornerLine(plane, rMax(zMin), zMin);

        if (p00 == null || p10 == null || p11 == null || p01 == null) {
            return null;
        }

        return new Point2D.Double[] {
                SliceProjection.projectToSlice(p00, phiDeg),
                SliceProjection.projectToSlice(p10, phiDeg),
                SliceProjection.projectToSlice(p11, phiDeg),
                SliceProjection.projectToSlice(p01, phiDeg)
        };
    }

    /**
     * Create a 3D wireframe representation of this shell.
     *
     * <p>
     * The returned lines trace the four boundaries at the minimum-phi side, the
     * four boundaries at the maximum-phi side, and the four azimuth-spanning
     * connector edges. This is meant for explanatory rendering in the companion
     * 3D view. The 2D slice view does not need these edges; it uses
     * {@link #slicePolygon(double)} instead.
     * </p>
     *
     * @return twelve finite 3D line segments forming the shell wireframe
     */
    public Line[] createWireframeEdges() {
        edu.cnu.mdi.geometry.Point[] c = createWireframeCorners();

        return new Line[] {
                // phi-min face
                new Line(c[0], c[1]),
                new Line(c[1], c[2]),
                new Line(c[2], c[3]),
                new Line(c[3], c[0]),

                // phi-max face
                new Line(c[4], c[5]),
                new Line(c[5], c[6]),
                new Line(c[6], c[7]),
                new Line(c[7], c[4]),

                // azimuth-spanning edges
                new Line(c[0], c[4]),
                new Line(c[1], c[5]),
                new Line(c[2], c[6]),
                new Line(c[3], c[7])
        };
    }

    /**
     * Create the eight shell corners used by the 3D wireframe.
     *
     * <p>
     * Corner order is:
     * </p>
     *
     * <pre>
     * 0..3: phi minimum side, around the z/r rectangle
     * 4..7: phi maximum side, matching the same rectangle order
     * </pre>
     *
     * @return eight 3D corner points
     */
    private edu.cnu.mdi.geometry.Point[] createWireframeCorners() {
        return new edu.cnu.mdi.geometry.Point[] {
                SliceProjection.cylindrical(rMin(zMin), PHI_MIN_DEG, zMin - SHELL_Z_SHIFT),
                SliceProjection.cylindrical(rMin(zMax), PHI_MIN_DEG, zMax - SHELL_Z_SHIFT),
                SliceProjection.cylindrical(rMax(zMax), PHI_MIN_DEG, zMax - SHELL_Z_SHIFT),
                SliceProjection.cylindrical(rMax(zMin), PHI_MIN_DEG, zMin - SHELL_Z_SHIFT),

                SliceProjection.cylindrical(rMin(zMin), PHI_MAX_DEG, zMin + SHELL_Z_SHIFT),
                SliceProjection.cylindrical(rMin(zMax), PHI_MAX_DEG, zMax + SHELL_Z_SHIFT),
                SliceProjection.cylindrical(rMax(zMax), PHI_MAX_DEG, zMax + SHELL_Z_SHIFT),
                SliceProjection.cylindrical(rMax(zMin), PHI_MAX_DEG, zMin + SHELL_Z_SHIFT)
        };
    }

    /**
     * Intersect one synthetic shell-corner line with the current phi plane.
     *
     * <p>
     * The line spans the sector from -30 degrees to +30 degrees in azimuth. Its
     * z coordinate is shifted across the span, mimicking the stereo-like tilt
     * used by the synthetic wire model. This is what makes the shell change
     * shape and position as the slider changes.
     * </p>
     *
     * @param plane current constant-phi plane
     * @param r radial coordinate of the corner line
     * @param z central z coordinate of the corner line
     * @return intersection point, or {@code null} if no segment intersection
     */
    private edu.cnu.mdi.geometry.Point intersectCornerLine(
            Plane plane, double r, double z) {

        edu.cnu.mdi.geometry.Point pMinus =
                SliceProjection.cylindrical(r, PHI_MIN_DEG, z - SHELL_Z_SHIFT);

        edu.cnu.mdi.geometry.Point pPlus =
                SliceProjection.cylindrical(r, PHI_MAX_DEG, z + SHELL_Z_SHIFT);

        Line line = new Line(pMinus, pPlus);

        edu.cnu.mdi.geometry.Point hit =
                new edu.cnu.mdi.geometry.Point();

        double t = plane.lineIntersection(line, hit);

        if (java.lang.Double.isNaN(t) || t < 0.0 || t > 1.0) {
            return null;
        }

        return hit;
    }

    /**
     * Return the inner radial envelope at the given z.
     *
     * @param z z coordinate
     * @return minimum radial coordinate
     */
    private double rMin(double z) {
        return chamberR0 + R_SLOPE * (z - chamberZ0) - R_MARGIN;
    }

    /**
     * Return the outer radial envelope at the given z.
     *
     * @param z z coordinate
     * @return maximum radial coordinate
     */
    private double rMax(double z) {
        return chamberR0
                + R_SLOPE * (z - chamberZ0)
                + (GeometrySliceModel.NUM_LAYERS - 1) * LAYER_SPACING
                + R_MARGIN;
    }
}
