package edu.cnu.mdi.view;

import java.util.Map;

/**
 * Base class for View Information.
 * Extend this for each View type to provide specific documentation.
 * It automatically assembles a standardized HTML string.
 */
public abstract class AbstractViewInfo {

    // --- Abstract Methods (Mandatory) ---
    public abstract String getTitle();
    public abstract String getPurpose();

    // --- Hook Methods (Override these if you have content) ---

    /**
     * @return Steps or instructions on how to use the view.
     */
    public String getUsage() {
        return null;
    }

    /**
     * @return A map of Key Combo -> Action (e.g., "Ctrl+S" -> "Save")
     */
    public Map<String, String> getKeyboardShortcuts() {
        return null;
    }

    /**
     * @return Technical notes (projections used, memory limits, etc.)
     */
    public String getTechnicalNotes() {
        return null;
    }

    /**
     * @return Authors, version numbers, or copyright info.
     */
    public String getFooter() {
        return "Generated by MDI Framework";
    }

    // --- HTML Generation Logic ---

    public String getAsHTML() {
        StringBuilder sb = new StringBuilder();

        // CSS Styling for Swing
        sb.append("<html><head><style>");
        sb.append("body { font-family: sans-serif; padding: 10px; color: #333; }");
        sb.append("h1 { color: #2c3e50; font-size: 16pt; margin-bottom: 5px; }");
        sb.append("h2 { color: #e67e22; font-size: 12pt; margin-top: 15px; margin-bottom: 5px; border-bottom: 1px solid #ccc; }");
        sb.append("p { margin-top: 5px; font-size: 10pt; }");
        sb.append("ul { margin-top: 5px; margin-left: 20px; }");
        sb.append("li { font-size: 10pt; margin-bottom: 3px; }");
        sb.append(".shortcut-key { font-weight: bold; font-family: monospace; color: #444; background-color: #eee; padding: 2px; }");
        sb.append(".footer { font-size: 8pt; color: #888; margin-top: 20px; border-top: 1px solid #eee; padding-top: 5px; }");
        sb.append("</style></head><body>");

        // 1. Title
        sb.append("<h1>").append(escape(getTitle())).append("</h1>");

        // 2. Purpose (Always present)
        sb.append("<p>").append(escape(getPurpose())).append("</p>");

        // 3. Usage Section (Conditional)
        String usage = getUsage();
        if (usage != null && !usage.isEmpty()) {
            sb.append("<h2>Usage</h2>");
            sb.append("<div>").append(usage).append("</div>"); // Usage might contain its own HTML tags like <br>
        }

        // 4. Shortcuts Section (Conditional)
        Map<String, String> shortcuts = getKeyboardShortcuts();
        if (shortcuts != null && !shortcuts.isEmpty()) {
            sb.append("<h2>Keyboard Shortcuts</h2>");
            sb.append("<ul>");
            for (Map.Entry<String, String> entry : shortcuts.entrySet()) {
                sb.append("<li>")
                  .append("<span class='shortcut-key'>").append(escape(entry.getKey())).append("</span> : ")
                  .append(escape(entry.getValue()))
                  .append("</li>");
            }
            sb.append("</ul>");
        }

        // 5. Technical Notes (Conditional)
        String tech = getTechnicalNotes();
        if (tech != null && !tech.isEmpty()) {
            sb.append("<h2>Technical Details</h2>");
            sb.append("<p><i>").append(escape(tech)).append("</i></p>");
        }

        // 6. Footer
        String footer = getFooter();
        if (footer != null) {
            sb.append("<div class='footer'>").append(escape(footer)).append("</div>");
        }

        sb.append("</body></html>");
        return sb.toString();
    }

    // Basic HTML escaping to prevent rendering errors
    private String escape(String s) {
        if (s == null) {
			return "";
		}
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\n", "<br>");
    }
}
